### ISSUE TITLE
Are G1/S transition cells not labeled  in cyclone?

### ISSUE THREAD

**Issue by TorteloteLab** [PMBio/cyclone#4]
Hi all, 
Thank you for this awesome tool. It is really useful. 
I am running cyclone on my scRNA seq data. I noticed the I have cells on G1, S or G2/M but not G1/S transition, and I expected to have several cells on G1/S transition. Can't cyclone label cells on G1/S transition? 
What happens to the G1/S transitioning cells within cyclone classifier? Are they labeled as S-phase cells?
Can you separate G2-phase cells from M-phase cells with cyclone?

Appreciate the feedback.

Best,

**Comment by antoscial** [comment]
Hello, 

Thanks for your email and your interest in the tool. 

Cyclone will only classify cells in G1, S or G2M, since these were the labels included in the training dataset - so you can’t distinguish G2- from M-phase cells (unless you have a separate dataset for training).

To identify cells that might be at G1/S transition, you would have to look at the individual scores calculated by cyclone: cells at G1/S transition will have a G1 score approximately equal to the S score (and much greater than the G2M score).


All the best,
Antonio

**Comment by TorteloteLab** [comment]
Thanks for the clarification.Appreciate it.
